// skill.test.mjs — the Claude Code door. Covers the three things that make the
// third door trustworthy: the bundle can't drift from src (parity), the node db
// adapter round-trips the SAME file the web reads, and the cli enforces its
// validate-or-write-nothing contract. Engine is (re)generated by `pretest`.

import { describe, it, expect, beforeAll, afterEach } from 'vitest';
import { readFileSync, writeFileSync, rmSync, existsSync, mkdtempSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { transformSource, ENGINE_FILES } from '../scripts/build-skill.mjs';
import { openDb, writeDb } from './db.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const cli = resolve(here, 'cli.mjs');

const tmpDb = () => resolve(mkdtempSync(resolve(tmpdir(), 'ikigaider-')), 'journey.sqlite');
const cleanup = [];
afterEach(() => { while (cleanup.length) { const p = cleanup.pop(); rmSync(dirname(p), { recursive: true, force: true }); } });

// Run cli.mjs as a real subprocess; return parsed stdout JSON. `input` is stdin.
function run(args, input) {
  const out = execFileSync('node', [cli, ...args], { input, encoding: 'utf8' });
  return JSON.parse(out);
}
// Run expecting a non-zero exit; return parsed stderr JSON.
function runFail(args, input) {
  try {
    execFileSync('node', [cli, ...args], { input, encoding: 'utf8' });
    throw new Error('expected non-zero exit');
  } catch (e) {
    expect(e.status).toBe(1);
    return JSON.parse(e.stderr);
  }
}

const SC = (p = {}) => ({ love: 0.5, good: 0.5, world: 0.5, paid: 0.5, ...p });
const act = (name, s = {}) => ({ name, scores: SC(s), conf: SC() });

describe('bundle parity — engine/*.mjs is a mechanical copy of src', () => {
  it('every engine module equals transformSource(its source)', () => {
    for (const [srcRel, outName] of ENGINE_FILES) {
      const want = transformSource(readFileSync(resolve(root, srcRel), 'utf8'));
      const got = readFileSync(resolve(here, 'engine', outName), 'utf8');
      expect(got, `${outName} drifted from ${srcRel} — run build:skill`).toBe(want);
    }
  });
  it('vendors the wasm binary + JS glue (no node_modules in the download)', () => {
    expect(existsSync(resolve(here, 'engine', 'sql-wasm.wasm'))).toBe(true);
    expect(existsSync(resolve(here, 'engine', 'sql-wasm.js'))).toBe(true);
  });
});

describe('db.mjs node adapter', () => {
  it('opens a missing path as a fresh version-stamped store', async () => {
    const p = tmpDb(); cleanup.push(p);
    const store = await openDb(p);
    expect(store.userVersion()).toBe(1000);
    expect(store.listActivities()).toEqual([]);
  });

  it('round-trips a journey through the same file the web reads (createDb both sides)', async () => {
    const p = tmpDb(); cleanup.push(p);
    const store = await openDb(p);
    const id = store.addActivity('craft');
    store.addScore(id, SC({ love: 0.9 }), SC(), 'assess');
    writeDb(store, p);

    // Reopen via the SAME createDb the web import uses (db.mjs wraps it).
    const reread = await openDb(p);
    expect(reread.listActivities()[0].name).toBe('craft');
    expect(reread.userVersion()).toBe(1000);
  });

  it('sanitized write carries no config (no api_key travels)', async () => {
    const p = tmpDb(); cleanup.push(p);
    const store = await openDb(p);
    store.setConfig({ base_url: 'http://secret', api_key: 'sk-LEAK', model: 'm' });
    store.addActivity('craft');
    writeDb(store, p, { sanitized: true });

    expect((await openDb(p)).getConfig()).toBeNull();
  });

  it('names a clear error on a corrupt file instead of throwing raw sql.js', async () => {
    const p = tmpDb(); cleanup.push(p);
    writeFileSync(p, Buffer.from('this is not a sqlite database'));
    await expect(openDb(p)).rejects.toThrow(/unreadable|corrupt/i);
  });
});

describe('cli.mjs — turn loop + validate-or-write-nothing', () => {
  it('init stamps and persists; state reads back empty', () => {
    const p = tmpDb(); cleanup.push(p);
    expect(run(['init', '--db', p]).userVersion).toBe(1000);
    const s = run(['state', '--db', p]);
    expect(s.portfolio).toEqual([]);
    expect(s.focalId).toBeNull();
  });

  it('prompt-assess emits the prompts.js messages + schema', () => {
    const p = tmpDb(); cleanup.push(p);
    const r = run(['prompt-assess', '--db', p, '--text', 'I build music tools']);
    expect(r.messages[0].role).toBe('system');
    expect(r.messages[1].content).toBe('I build music tools');
    expect(r.schema.name).toBe('ikigai_assessment');
  });

  it('append-assessment places the activity and decides a move', () => {
    const p = tmpDb(); cleanup.push(p);
    run(['init', '--db', p]);
    const r = run(['append-assessment', '--db', p],
      JSON.stringify({ activities: [act('music tools', { love: 0.9, good: 0.5, world: 0.4, paid: 0.2 })] }));
    expect(r.kind).toBe('placed');
    expect(r.createdIds).toHaveLength(1);
    expect(r.focalId).toBe(r.createdIds[0]);
    expect(r.move).toBeTruthy();
  });

  it('an empty assessment signals interview', () => {
    const p = tmpDb(); cleanup.push(p);
    run(['init', '--db', p]);
    expect(run(['append-assessment', '--db', p], JSON.stringify({ activities: [] })).kind).toBe('interview');
  });

  it('append-move coaches toward the decided move and reports the next', () => {
    const p = tmpDb(); cleanup.push(p);
    run(['init', '--db', p]);
    const seeded = run(['append-assessment', '--db', p],
      JSON.stringify({ activities: [act('music tools', { love: 0.9, good: 0.5, world: 0.4, paid: 0.2 }), act('day job', { love: 0.2, good: 0.85, world: 0.6, paid: 0.9 })] }));
    const r = run(['append-move', '--db', p, '--focal', seeded.focalId, '--user-text', 'charging now'],
      JSON.stringify({ message: 'charge for one tool', updates: [], created: [] }));
    expect(r.message).toBe('charge for one tool');
    expect(r.nextMove).toBeTruthy();
  });

  it('export writes a sanitized handoff file and points at the web', () => {
    const p = tmpDb(); cleanup.push(p);
    run(['init', '--db', p]);
    const out = resolve(dirname(p), 'handoff.sqlite');
    const r = run(['export', '--db', p, '--out', out]);
    expect(r.exported).toBe(out);
    expect(existsSync(out)).toBe(true);
  });

  it('schema-invalid assessment writes NOTHING and asks for one retry', () => {
    const p = tmpDb(); cleanup.push(p);
    run(['init', '--db', p]);
    const err = runFail(['append-assessment', '--db', p],
      JSON.stringify({ activities: [{ name: 'x', scores: { love: 0.5 } }] })); // missing conf + axes
    expect(err.retry).toBe(true);
    expect(err.errors.length).toBeGreaterThan(0);
    expect(run(['state', '--db', p]).portfolio).toEqual([]); // nothing written
  });

  it('malformed stdin JSON is a structured error, not a stack trace', () => {
    const p = tmpDb(); cleanup.push(p);
    run(['init', '--db', p]);
    expect(runFail(['append-assessment', '--db', p], 'not json').error).toMatch(/not valid JSON/);
  });

  it('an unknown command errors with the command list', () => {
    expect(runFail(['frobnicate']).error).toMatch(/Unknown command/);
  });
});
